name: Build React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn install
    - run: yarn client:build
    - name: Upload a app.js Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: react-app
        path: built/app.js
    
